// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoU0q5WTFkn3cdW1AOIhEM00Y52D4RE5E',
    appId: '1:415548333011:web:07868b76bead3d845bad26',
    messagingSenderId: '415548333011',
    projectId: 'smart-medical-caddy',
    authDomain: 'smart-medical-caddy.firebaseapp.com',
    databaseURL: 'https://smart-medical-caddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medical-caddy.appspot.com',
    measurementId: 'G-KD43P04W2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDaEJlY0Amkz-PLpyMDvgO7YaFhc7Rfo',
    appId: '1:415548333011:android:01e5fc33ba31943a5bad26',
    messagingSenderId: '415548333011',
    projectId: 'smart-medical-caddy',
    databaseURL: 'https://smart-medical-caddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medical-caddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7SjR0S2tug76CESPx_-QoegKJElLHHpE',
    appId: '1:415548333011:ios:76e51a31dcfe73e65bad26',
    messagingSenderId: '415548333011',
    projectId: 'smart-medical-caddy',
    databaseURL: 'https://smart-medical-caddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medical-caddy.appspot.com',
    iosClientId: '415548333011-0b389ro49e4q3juqsnvrn4ucs5qrbpnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7SjR0S2tug76CESPx_-QoegKJElLHHpE',
    appId: '1:415548333011:ios:76e51a31dcfe73e65bad26',
    messagingSenderId: '415548333011',
    projectId: 'smart-medical-caddy',
    databaseURL: 'https://smart-medical-caddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medical-caddy.appspot.com',
    iosClientId: '415548333011-0b389ro49e4q3juqsnvrn4ucs5qrbpnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicine',
  );
}
